# Generated by Django 3.2.9 on 2021-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceIdentity',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('imageUrl', models.URLField()),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
