# Generated by Django 3.2.9 on 2021-11-20 13:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidentity',
            name='encodedFace',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
