# Generated by Django 3.2.9 on 2021-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_faceidentity_encodedface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceidentity',
            name='encodedFace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
